# travis need to have provided language type to start proper build process.
language: csharp

# csharp build is started with mono, so need to disable mono and include dotnet
mono: none
dotnet: 1.0.3
dist: trusty

script:
  - dotnet restore --verbosity quiet nippin.sln
  # in Release docker build is unchecked - it doesn't work on Travis
  - dotnet build /p:Configuration=Release nippin.sln
  - dotnet build /p:Configuration=Release nippin.sln
  - dotnet test Backend.Tests/Backend.Tests.csproj
  - dotnet test Endpoint.Tests/Endpoint.Tests.csproj
  
# sudo is required for docker https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker

