# travis need to have provided language type to start proper build process.
language: csharp

# csharp build is started with mono, so need to disable mono and include dotnet
mono: none
dotnet: 1.0.3
dist: trusty

script:
  - dotnet restore --verbosity quiet nippin.sln

  # run well-known test's projects. If you would like to add new test projects
  # it needs to be included in that place.
  - dotnet test -c Release Backend.Tests/Backend.Tests.csproj
  - dotnet test -c Release Endpoint.Tests/Endpoint.Tests.csproj
  
  # produce artifacts and pack them to docker image
  - dotnet publish /p:Configuration=Release -o publish Endpoint/Endpoint.csproj
  - docker build -t siudeks/nippin Endpoint/publish

# sudo is required for docker https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker

after_success:
  # push application image to docker registry
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push siudeks/nippin;
    fi


