version: '3'
services:
  backend:
    build: Endpoint/Publish
    image: 'siudeks/nippin:latest'
    ports:
      - '80:5000'
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  seleniumgrid:
    image: 'selenium/standalone-chrome:3.3.1'
    ports:
      - '4444:4444'
    
